services:
  - type: web
    name: workers-marketplace-client
    env: static
    rootDirectory: client
    buildCommand: npm run build:static
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://workersplace.onrender.com/api
